# Generated by Django 5.0.1 on 2024-02-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body_en',
            new_name='body_english',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body_km',
            new_name='body_khmer',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_en',
            new_name='title_english',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_km',
            new_name='title_khmer',
        ),
    ]
