# Generated by Django 5.0.1 on 2024-02-26 17:50

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_body_en_post_body_english_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_english',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_khmer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_english',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_khmer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_khmer', models.CharField(max_length=255)),
                ('body_khmer', ckeditor.fields.RichTextField()),
                ('title_english', models.CharField(max_length=255)),
                ('body_english', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
