# Generated by Django 5.0.1 on 2024-02-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_category_blogpostcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostcategory',
            old_name='categoryName',
            new_name='categoryNameEnglish',
        ),
        migrations.AddField(
            model_name='blogpostcategory',
            name='categoryNameKhmer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
